var GAME_LEVELS = [
   ["                                                                                                     ",
   "                                                                                                      ",
   "                                                                                                      ",
   "                                                                                                      ",
   "                                                                                                      ",
   "                                            *                                                         ",
   "                               *                         0000     *                                   ",
   "                                       *                000000         *                  *           ",
   "              *                xxx*                    00000000                *                      ",
   "         *                  * x!!!x                     000000                                        ",
   "                              x!!!x         *            0000    xxxxxx                         *     ",
   "                   *           x!x                                ooo x *                             ",
   "         *                      v              oo                ooooox                  *             ",
   "                          *     o              xx                            *                        ",
   "  xx                   o                              oo       x  *                              xxxxx",
   "  x                                      xxxxx        xx                                          xxxx",
   "  x                   yyy   o      o     yyyyy                    x                             o xxxx",
   "  x                   xxx                  o               yyyyy                                  xxxx",
   "  x    o   @     o                        o o              xxxxx               o      o         # xxxx",
   "  xxxxxxxxyyyyyyxxxxxxxxxxxyyxx   xxxyyxxxxxxxxx     xyyxxxxxxxxxxxyyyxxxxx   xxx    xxx     xxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxx                  xxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxyyyyyyyy!!!!!!!!!!xxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxyyyyyyyy!!!!!!!!!!xxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                       ",
   "                                                                                                       ",
   "                                                                                                       ",
   "                                                                                                       ",
   "                                   *                                                                   ",
   "                               *                                                                       ",
   "                 *                               *                                                     ",
   "                                                        *                          *                   ",
   "       *                                *                             *                             *  ",
   "                     *                                 0000                                            ",
   "                           yo#oy                      000000     oo                      *             ",
   "                           xxxxx      xxx       *    00000000    xx            *                       ",
   "        *      oo                    x!!!x            000000                                 *         ",
   "               xx     oo             xvvvx             0000                 oo                         ",
   "                      xx      *                                             xx                         ",
   "                                                   *                                                   ",
   "xxx         *                                                        x             xxx    xx        xxx",
   "xx                                                              oyo                                @ xx",
   "xx                          xx                               xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx",
   "xx                  xx                ooo                xxxy!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xx                                                  xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxyyyyyyyyyyyyyyyyyyyxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                           ",
   "                                                                                           ",
   "    @                                                                                      ",
   "   xxx                   *                                            *                    ",
   "          *                                      *                                         ",
   "            o                *  xxxxx                      *                               ",
   "           xxx    *             x!!!x                                        *             ",
   "                                x!!!x                                                      ",
   "       xxx                      xvvvx                         *                            ",
   "                y      yooy            xxxxxxxxxxxxxxxxxxxx                                ",
   "               xxx     yooy            x                   *                *              ",
   "      x                yooy            xxx      *                                          ",
   "                       yooy            x x                                                 ",
   "                       yooy     *      x x                                                 ",
   "          x            yooy          xxx xxx        *       x                 o            ",
   "                o                         x               x   oooo   x       xxx           ",
   "               xxx                        x         o       xoooooooooooox       o         ",
   "                        xx                x         oo      xxxxxyyyxxxxx       xxx        ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!xxx             xx  #   x   x     xxxxxxxxxxxxx                  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx o    x   xxxxxxxxxyyyxxxxxxxx               xxx           ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx   x   xxxxxxxxxxxxx                    o               ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxx o x                *                               ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx o xx                             xxxx      *       ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx o x=          x            xxx                     ",
   "                                      x o x    *xx    x        *  o           o            ",
   "                                      x o x          =x     o    xxx         xxxx           ",
   "                *                     x o x     xx    x                      x!!!x  o      ",
   "                              o   o   x o x    *            xxx        xxx           xxx   ",
   "                                        o                                            x!!x  ",
   "         *                                       o o   xooooooooooooox               xvvx  ",
   "  x                          xxxxxxx xxxxxx          xoooooooooooooox                      ",
   "  x                  *        x           x   xxxxxxxxxxxxxxxxxxxxxxx        *             ",
   "  x                          xx     o     x                                                ",
   "  x                           x     x     x     *                                xxxoyx!!!x",
   "  x                           x    xxx    x                                      xxxxxxxxxx",
   "  xyyyyyyyyyyyyyyyyyyyyyyyyyyyx!!!!xxx!!!!xxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!xxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!xxxxxxxxxx",
   "                                                                                            "],
  ["                                                                           ",
   "                                                                           ",
   "           ***           ***         ***********         ****       ****   ",
   "            ***         ***         ****     ****        ****       ****   ",
   "             ***       ***          ****     ****        ****       ****   ",
   "              ***     ***           ****     ****        ****       ****   ",
   "               ***   ***            ****     ****        ****       ****   ",
   "                *** ***             ****     ****        ****       ****   ",
   "                 *****              ****     ****        ****       ****   ",
   "                  ***               ****     ****        ****       ****   ",
   "                  ***               ****     ****        ****       ****   ",
   "                  ***               ****     ****        ****       ****   ",
   "                  ***                ***********          *************    ",
  "                                                                            ",
   "                                                                           ",
   "           ****           ****          ***           ****        ****     ",
   "           ****           ****          ***           **** *      ****     ",
   "           ****           ****          ***           ****  **    ****     ",
   "           ****           ****          ***           ****  ***   ****     ",
   "           ****    ****   ****          ***           ****  ****  ****     ",
   "           ****    ****   ****          ***           ****   **** ****     ",
   "            ***    ****   ***           ***           ****    ********     ",
   "              ****    ****              ***           ****      ******     ",
   "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo ",
   "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo ",
   "oooooooooooooooooooooooooooooooooo@ooooooooooooooooooooooooooooooooooooooo ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
